<?php

namespace Database\Seeders;

use App\Models\Part;
use Illuminate\Database\Seeder;

class PartSeeder extends Seeder
{
    public function run(): void
    {
        $parts = [

            // ── TOYOTA AQUA (2017–2021) ───────────────────────────────────────
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Aqua', 'vehicle_year_from' => 2017, 'vehicle_year_to' => 2021, 'part_name' => 'Engine Oil Filter',        'part_category' => 'Engine',      'oem_part_number' => '90915-YZZD2', 'alternative_part_number' => 'W67',        'brand' => 'Toyota Genuine', 'description' => 'OEM oil filter for 1NZ-FXE hybrid engine. Replace every 5,000 km with oil change.'],
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Aqua', 'vehicle_year_from' => 2017, 'vehicle_year_to' => 2021, 'part_name' => 'Air Filter',               'part_category' => 'Engine',      'oem_part_number' => '17801-21050', 'alternative_part_number' => 'A1702',      'brand' => 'Toyota Genuine', 'description' => 'Engine air filter for 1NZ-FXE. Prevents dust and debris from entering the engine.'],
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Aqua', 'vehicle_year_from' => 2017, 'vehicle_year_to' => 2021, 'part_name' => 'Spark Plugs (Set of 4)',   'part_category' => 'Engine',      'oem_part_number' => '90919-01253', 'alternative_part_number' => 'IFR6T11',    'brand' => 'Denso',          'description' => 'Iridium spark plugs for Toyota Aqua 1NZ-FXE hybrid engine. Long-lasting performance.'],
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Aqua', 'vehicle_year_from' => 2017, 'vehicle_year_to' => 2021, 'part_name' => 'Front Brake Pads',        'part_category' => 'Brakes',      'oem_part_number' => '04465-52220', 'alternative_part_number' => 'D1187',      'brand' => 'Toyota Genuine', 'description' => 'Front disc brake pads for Toyota Aqua. Includes wear indicator for safety.'],
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Aqua', 'vehicle_year_from' => 2017, 'vehicle_year_to' => 2021, 'part_name' => 'Cabin Air Filter',         'part_category' => 'Interior',    'oem_part_number' => '87139-52040', 'alternative_part_number' => 'CAF1827',    'brand' => 'Toyota Genuine', 'description' => 'Pollen/cabin air filter for Toyota Aqua HVAC system. Replace every 15,000 km.'],
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Aqua', 'vehicle_year_from' => 2017, 'vehicle_year_to' => 2021, 'part_name' => 'Wiper Blade Set',          'part_category' => 'Exterior',    'oem_part_number' => '85212-12790', 'alternative_part_number' => 'WB-AQ17',    'brand' => 'Bosch',          'description' => 'Front wiper blade set for Toyota Aqua. Driver 650mm, passenger 400mm.'],
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Aqua', 'vehicle_year_from' => 2017, 'vehicle_year_to' => 2021, 'part_name' => 'Hybrid Battery Coolant Fan','part_category' => 'Hybrid System','oem_part_number' => '16711-21080', 'alternative_part_number' => null,         'brand' => 'Toyota Genuine', 'description' => 'Cooling fan for the hybrid battery pack. Essential for battery temperature management.'],

            // ── HONDA VEZEL (2019–2022) ───────────────────────────────────────
            ['vehicle_make' => 'Honda', 'vehicle_model' => 'Vezel', 'vehicle_year_from' => 2019, 'vehicle_year_to' => 2022, 'part_name' => 'Engine Oil Filter',        'part_category' => 'Engine',      'oem_part_number' => '15400-RTA-003', 'alternative_part_number' => 'HO-3593',  'brand' => 'Honda Genuine',  'description' => 'OEM oil filter for Honda Vezel LEB hybrid engine. Replace every 5,000 km.'],
            ['vehicle_make' => 'Honda', 'vehicle_model' => 'Vezel', 'vehicle_year_from' => 2019, 'vehicle_year_to' => 2022, 'part_name' => 'Air Filter',               'part_category' => 'Engine',      'oem_part_number' => '17220-5PA-A00', 'alternative_part_number' => 'A1623',    'brand' => 'Honda Genuine',  'description' => 'Engine air filter for Honda Vezel 1.5L hybrid. Replace every 15,000 km.'],
            ['vehicle_make' => 'Honda', 'vehicle_model' => 'Vezel', 'vehicle_year_from' => 2019, 'vehicle_year_to' => 2022, 'part_name' => 'Spark Plugs (Set of 4)',   'part_category' => 'Engine',      'oem_part_number' => '12290-5PA-A01', 'alternative_part_number' => 'IZFR6K13', 'brand' => 'NGK',            'description' => 'Laser iridium spark plugs for Honda Vezel 1.5L DOHC i-VTEC engine.'],
            ['vehicle_make' => 'Honda', 'vehicle_model' => 'Vezel', 'vehicle_year_from' => 2019, 'vehicle_year_to' => 2022, 'part_name' => 'Front Brake Pads',        'part_category' => 'Brakes',      'oem_part_number' => '45022-T7A-J51', 'alternative_part_number' => 'D1556',    'brand' => 'Honda Genuine',  'description' => 'Front brake pads for Honda Vezel. Low-dust formula with wear indicator.'],
            ['vehicle_make' => 'Honda', 'vehicle_model' => 'Vezel', 'vehicle_year_from' => 2019, 'vehicle_year_to' => 2022, 'part_name' => 'Cabin Air Filter',         'part_category' => 'Interior',    'oem_part_number' => '80292-TF0-G01', 'alternative_part_number' => 'CAF1895',  'brand' => 'Honda Genuine',  'description' => 'Cabin pollen filter for Honda Vezel. Filters dust, pollen and harmful particles.'],
            ['vehicle_make' => 'Honda', 'vehicle_model' => 'Vezel', 'vehicle_year_from' => 2019, 'vehicle_year_to' => 2022, 'part_name' => 'Wiper Blade Set',          'part_category' => 'Exterior',    'oem_part_number' => '76620-TF0-G01', 'alternative_part_number' => 'WB-VZ19',  'brand' => 'Bosch',          'description' => 'Front wiper blade set for Honda Vezel. Driver 650mm, passenger 400mm.'],
            ['vehicle_make' => 'Honda', 'vehicle_model' => 'Vezel', 'vehicle_year_from' => 2019, 'vehicle_year_to' => 2022, 'part_name' => 'CVT Transmission Fluid',   'part_category' => 'Transmission','oem_part_number' => '08200-9006',    'alternative_part_number' => null,       'brand' => 'Honda Genuine',  'description' => 'Honda Genuine CVT fluid for Vezel. Required for smooth CVT operation. Replace every 30,000 km.'],

            // ── TOYOTA PRIUS (2015–2018) ──────────────────────────────────────
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Prius', 'vehicle_year_from' => 2015, 'vehicle_year_to' => 2018, 'part_name' => 'Engine Oil Filter',       'part_category' => 'Engine',      'oem_part_number' => '90915-YZZD2',  'alternative_part_number' => 'W67',      'brand' => 'Toyota Genuine', 'description' => 'OEM oil filter for Toyota Prius 1.8L 2ZR-FXE hybrid engine.'],
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Prius', 'vehicle_year_from' => 2015, 'vehicle_year_to' => 2018, 'part_name' => 'Air Filter',              'part_category' => 'Engine',      'oem_part_number' => '17801-37021',  'alternative_part_number' => 'A3205',    'brand' => 'Toyota Genuine', 'description' => 'Engine air filter for Toyota Prius 4th generation 1.8L hybrid.'],
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Prius', 'vehicle_year_from' => 2015, 'vehicle_year_to' => 2018, 'part_name' => 'Spark Plugs (Set of 4)',  'part_category' => 'Engine',      'oem_part_number' => '90919-01253',  'alternative_part_number' => 'SK20HR11', 'brand' => 'Denso',          'description' => 'Iridium spark plugs for Toyota Prius 2ZR-FXE. Excellent fuel efficiency and longevity.'],
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Prius', 'vehicle_year_from' => 2015, 'vehicle_year_to' => 2018, 'part_name' => 'Front Brake Pads',       'part_category' => 'Brakes',      'oem_part_number' => '04465-47080',  'alternative_part_number' => 'D1553',    'brand' => 'Toyota Genuine', 'description' => 'Front brake pads for Toyota Prius 4th gen. Regenerative braking compatible.'],
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Prius', 'vehicle_year_from' => 2015, 'vehicle_year_to' => 2018, 'part_name' => 'Cabin Air Filter',        'part_category' => 'Interior',    'oem_part_number' => '87139-47010',  'alternative_part_number' => 'CAF1895',  'brand' => 'Toyota Genuine', 'description' => 'Cabin air/pollen filter for Toyota Prius 4th generation.'],
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Prius', 'vehicle_year_from' => 2015, 'vehicle_year_to' => 2018, 'part_name' => 'Wiper Blade Set',         'part_category' => 'Exterior',    'oem_part_number' => '85212-47050',  'alternative_part_number' => 'WB-PR15',  'brand' => 'Bosch',          'description' => 'Front wiper blades for Toyota Prius 4th gen. Driver 650mm, passenger 350mm.'],
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Prius', 'vehicle_year_from' => 2015, 'vehicle_year_to' => 2018, 'part_name' => 'Inverter Coolant Pump',   'part_category' => 'Hybrid System','oem_part_number' => '04000-32528',  'alternative_part_number' => null,       'brand' => 'Toyota Genuine', 'description' => 'Electric coolant pump for hybrid inverter system. Critical for hybrid system cooling.'],

            // ── MAZDA DEMIO (2014–2019) ───────────────────────────────────────
            ['vehicle_make' => 'Mazda', 'vehicle_model' => 'Demio', 'vehicle_year_from' => 2014, 'vehicle_year_to' => 2019, 'part_name' => 'Engine Oil Filter',        'part_category' => 'Engine',      'oem_part_number' => 'PE01-14-302A', 'alternative_part_number' => 'OC295',    'brand' => 'Mazda Genuine',  'description' => 'OEM oil filter for Mazda Demio 1.3L P3-VPS / 1.5L P5-VPS SKYACTIV engine.'],
            ['vehicle_make' => 'Mazda', 'vehicle_model' => 'Demio', 'vehicle_year_from' => 2014, 'vehicle_year_to' => 2019, 'part_name' => 'Air Filter',               'part_category' => 'Engine',      'oem_part_number' => 'PE01-13-3A0',  'alternative_part_number' => 'A1712',    'brand' => 'Mazda Genuine',  'description' => 'Engine air filter for Mazda Demio SKYACTIV-G 1.3L/1.5L.'],
            ['vehicle_make' => 'Mazda', 'vehicle_model' => 'Demio', 'vehicle_year_from' => 2014, 'vehicle_year_to' => 2019, 'part_name' => 'Spark Plugs (Set of 4)',   'part_category' => 'Engine',      'oem_part_number' => 'PE2R-18-110',  'alternative_part_number' => 'ILZKAR7B', 'brand' => 'NGK',            'description' => 'Iridium spark plugs for Mazda Demio SKYACTIV-G engine. OE specification.'],
            ['vehicle_make' => 'Mazda', 'vehicle_model' => 'Demio', 'vehicle_year_from' => 2014, 'vehicle_year_to' => 2019, 'part_name' => 'Front Brake Pads',        'part_category' => 'Brakes',      'oem_part_number' => 'B45Y-33-28Z',  'alternative_part_number' => 'D1576',    'brand' => 'Mazda Genuine',  'description' => 'Front disc brake pads for Mazda Demio DJ series.'],
            ['vehicle_make' => 'Mazda', 'vehicle_model' => 'Demio', 'vehicle_year_from' => 2014, 'vehicle_year_to' => 2019, 'part_name' => 'Cabin Air Filter',         'part_category' => 'Interior',    'oem_part_number' => 'K122-61-J6X',  'alternative_part_number' => 'CAF1812',  'brand' => 'Mazda Genuine',  'description' => 'Cabin air/pollen filter for Mazda Demio DJ. Removes dust and allergens from cabin air.'],
            ['vehicle_make' => 'Mazda', 'vehicle_model' => 'Demio', 'vehicle_year_from' => 2014, 'vehicle_year_to' => 2019, 'part_name' => 'Wiper Blade Set',          'part_category' => 'Exterior',    'oem_part_number' => 'D651-67-330',  'alternative_part_number' => 'WB-DM14',  'brand' => 'Bosch',          'description' => 'Front wiper blade set for Mazda Demio DJ. Driver 600mm, passenger 400mm.'],
            ['vehicle_make' => 'Mazda', 'vehicle_model' => 'Demio', 'vehicle_year_from' => 2014, 'vehicle_year_to' => 2019, 'part_name' => 'Fuel Filter',              'part_category' => 'Fuel System', 'oem_part_number' => 'PE01-13-480',  'alternative_part_number' => 'FF0145',   'brand' => 'Mazda Genuine',  'description' => 'In-tank fuel filter for Mazda Demio SKYACTIV-G. Keeps fuel system clean.'],

            // ── SUZUKI SWIFT (2017–2022) ──────────────────────────────────────
            ['vehicle_make' => 'Suzuki', 'vehicle_model' => 'Swift', 'vehicle_year_from' => 2017, 'vehicle_year_to' => 2022, 'part_name' => 'Engine Oil Filter',       'part_category' => 'Engine',      'oem_part_number' => '16510-61A31',  'alternative_part_number' => 'W712',     'brand' => 'Suzuki Genuine', 'description' => 'OEM oil filter for Suzuki Swift 1.2L K12C DualJet engine.'],
            ['vehicle_make' => 'Suzuki', 'vehicle_model' => 'Swift', 'vehicle_year_from' => 2017, 'vehicle_year_to' => 2022, 'part_name' => 'Air Filter',              'part_category' => 'Engine',      'oem_part_number' => '13780-70J10',  'alternative_part_number' => 'A1715',    'brand' => 'Suzuki Genuine', 'description' => 'Engine air filter for Suzuki Swift 4th gen 1.2L K12C engine.'],
            ['vehicle_make' => 'Suzuki', 'vehicle_model' => 'Swift', 'vehicle_year_from' => 2017, 'vehicle_year_to' => 2022, 'part_name' => 'Spark Plugs (Set of 4)',  'part_category' => 'Engine',      'oem_part_number' => '09482-00528',  'alternative_part_number' => 'ILZKR7B',  'brand' => 'NGK',            'description' => 'Iridium spark plugs for Suzuki Swift K12C DualJet. Extended service interval.'],
            ['vehicle_make' => 'Suzuki', 'vehicle_model' => 'Swift', 'vehicle_year_from' => 2017, 'vehicle_year_to' => 2022, 'part_name' => 'Front Brake Pads',       'part_category' => 'Brakes',      'oem_part_number' => '55810-62J01',  'alternative_part_number' => 'D1547',    'brand' => 'Suzuki Genuine', 'description' => 'Front disc brake pads for Suzuki Swift 4th generation.'],
            ['vehicle_make' => 'Suzuki', 'vehicle_model' => 'Swift', 'vehicle_year_from' => 2017, 'vehicle_year_to' => 2022, 'part_name' => 'Cabin Air Filter',        'part_category' => 'Interior',    'oem_part_number' => '95860-68L00',  'alternative_part_number' => 'CAF1798',  'brand' => 'Suzuki Genuine', 'description' => 'Cabin pollen filter for Suzuki Swift. Filters dust, pollen and fine particles.'],
            ['vehicle_make' => 'Suzuki', 'vehicle_model' => 'Swift', 'vehicle_year_from' => 2017, 'vehicle_year_to' => 2022, 'part_name' => 'Wiper Blade Set',         'part_category' => 'Exterior',    'oem_part_number' => '38340-68L10',  'alternative_part_number' => 'WB-SW17',  'brand' => 'Bosch',          'description' => 'Front wiper blade set for Suzuki Swift 4th gen. Driver 550mm, passenger 400mm.'],
            ['vehicle_make' => 'Suzuki', 'vehicle_model' => 'Swift', 'vehicle_year_from' => 2017, 'vehicle_year_to' => 2022, 'part_name' => 'Timing Chain Kit',        'part_category' => 'Engine',      'oem_part_number' => '12721-68L00',  'alternative_part_number' => null,       'brand' => 'Suzuki Genuine', 'description' => 'Timing chain and tensioner kit for Suzuki Swift K12C engine. Inspect at 60,000 km.'],

            // ── NISSAN LEAF (2018–2022) ───────────────────────────────────────
            ['vehicle_make' => 'Nissan', 'vehicle_model' => 'Leaf', 'vehicle_year_from' => 2018, 'vehicle_year_to' => 2022, 'part_name' => 'Cabin Air Filter',          'part_category' => 'Interior',     'oem_part_number' => '27277-5RA0A',  'alternative_part_number' => 'CAF1902',  'brand' => 'Nissan Genuine',  'description' => 'Cabin air/pollen filter for Nissan Leaf ZE1. Filters dust and allergens from cabin air.'],
            ['vehicle_make' => 'Nissan', 'vehicle_model' => 'Leaf', 'vehicle_year_from' => 2018, 'vehicle_year_to' => 2022, 'part_name' => 'Front Brake Pads',          'part_category' => 'Brakes',       'oem_part_number' => 'D1060-5SA0A',  'alternative_part_number' => 'D1672',    'brand' => 'Nissan Genuine',  'description' => 'Front disc brake pads for Nissan Leaf ZE1. Compatible with regenerative braking system.'],
            ['vehicle_make' => 'Nissan', 'vehicle_model' => 'Leaf', 'vehicle_year_from' => 2018, 'vehicle_year_to' => 2022, 'part_name' => 'Rear Brake Pads',           'part_category' => 'Brakes',       'oem_part_number' => 'D4060-5SA0A',  'alternative_part_number' => 'D1673',    'brand' => 'Nissan Genuine',  'description' => 'Rear disc brake pads for Nissan Leaf ZE1.'],
            ['vehicle_make' => 'Nissan', 'vehicle_model' => 'Leaf', 'vehicle_year_from' => 2018, 'vehicle_year_to' => 2022, 'part_name' => 'Wiper Blade Set',            'part_category' => 'Exterior',     'oem_part_number' => '28890-3NF0A',  'alternative_part_number' => 'WB-LF18',  'brand' => 'Bosch',           'description' => 'Front wiper blade set for Nissan Leaf ZE1. Driver 650mm, passenger 400mm.'],
            ['vehicle_make' => 'Nissan', 'vehicle_model' => 'Leaf', 'vehicle_year_from' => 2018, 'vehicle_year_to' => 2022, 'part_name' => 'Brake Fluid DOT 3',         'part_category' => 'Brakes',       'oem_part_number' => 'KE903-00031',  'alternative_part_number' => null,        'brand' => 'Nissan Genuine',  'description' => 'DOT 3 brake fluid for Nissan Leaf. Essential for maintaining braking performance. Replace every 20,000 km.'],
            ['vehicle_make' => 'Nissan', 'vehicle_model' => 'Leaf', 'vehicle_year_from' => 2018, 'vehicle_year_to' => 2022, 'part_name' => 'Battery Coolant',            'part_category' => 'EV System',    'oem_part_number' => 'KE902-00042',  'alternative_part_number' => null,        'brand' => 'Nissan Genuine',  'description' => 'Lithium-ion battery pack coolant for Nissan Leaf ZE1. Maintains optimal battery temperature.'],
            ['vehicle_make' => 'Nissan', 'vehicle_model' => 'Leaf', 'vehicle_year_from' => 2018, 'vehicle_year_to' => 2022, 'part_name' => 'Reduction Gear Oil',         'part_category' => 'Transmission', 'oem_part_number' => 'KE616-00032',  'alternative_part_number' => null,        'brand' => 'Nissan Genuine',  'description' => 'Reduction gear lubricant for Nissan Leaf electric motor gearbox. Replace every 30,000 km.'],

            // ── HONDA FIT (2015–2020) ─────────────────────────────────────────
            ['vehicle_make' => 'Honda', 'vehicle_model' => 'Fit', 'vehicle_year_from' => 2015, 'vehicle_year_to' => 2020, 'part_name' => 'Engine Oil Filter',           'part_category' => 'Engine',       'oem_part_number' => '15400-RTA-003', 'alternative_part_number' => 'HO-3593', 'brand' => 'Honda Genuine',  'description' => 'OEM oil filter for Honda Fit GK 1.3L/1.5L L13B/L15B engine. Replace every 5,000 km.'],
            ['vehicle_make' => 'Honda', 'vehicle_model' => 'Fit', 'vehicle_year_from' => 2015, 'vehicle_year_to' => 2020, 'part_name' => 'Air Filter',                  'part_category' => 'Engine',       'oem_part_number' => '17220-5R0-000', 'alternative_part_number' => 'A1623',   'brand' => 'Honda Genuine',  'description' => 'Engine air filter for Honda Fit GK 1.3L/1.5L. Replace every 15,000 km.'],
            ['vehicle_make' => 'Honda', 'vehicle_model' => 'Fit', 'vehicle_year_from' => 2015, 'vehicle_year_to' => 2020, 'part_name' => 'Spark Plugs (Set of 4)',      'part_category' => 'Engine',       'oem_part_number' => '12290-5R0-003', 'alternative_part_number' => 'IZFR6K11','brand' => 'NGK',            'description' => 'Iridium spark plugs for Honda Fit GK L13B/L15B engine.'],
            ['vehicle_make' => 'Honda', 'vehicle_model' => 'Fit', 'vehicle_year_from' => 2015, 'vehicle_year_to' => 2020, 'part_name' => 'Front Brake Pads',            'part_category' => 'Brakes',       'oem_part_number' => '45022-T5A-J51', 'alternative_part_number' => 'D1556',   'brand' => 'Honda Genuine',  'description' => 'Front disc brake pads for Honda Fit GK series.'],
            ['vehicle_make' => 'Honda', 'vehicle_model' => 'Fit', 'vehicle_year_from' => 2015, 'vehicle_year_to' => 2020, 'part_name' => 'Cabin Air Filter',            'part_category' => 'Interior',     'oem_part_number' => '80292-T5R-A01', 'alternative_part_number' => 'CAF1812', 'brand' => 'Honda Genuine',  'description' => 'Cabin pollen filter for Honda Fit GK. Removes dust and allergens from cabin.'],
            ['vehicle_make' => 'Honda', 'vehicle_model' => 'Fit', 'vehicle_year_from' => 2015, 'vehicle_year_to' => 2020, 'part_name' => 'Wiper Blade Set',             'part_category' => 'Exterior',     'oem_part_number' => '76620-T5A-003', 'alternative_part_number' => 'WB-FT15', 'brand' => 'Bosch',          'description' => 'Front wiper blade set for Honda Fit GK. Driver 600mm, passenger 400mm.'],
            ['vehicle_make' => 'Honda', 'vehicle_model' => 'Fit', 'vehicle_year_from' => 2015, 'vehicle_year_to' => 2020, 'part_name' => 'CVT Transmission Fluid',      'part_category' => 'Transmission', 'oem_part_number' => '08200-9006',    'alternative_part_number' => null,      'brand' => 'Honda Genuine',  'description' => 'Honda Genuine CVT fluid for Fit GK. Required for smooth CVT operation. Replace every 30,000 km.'],

            // ── TOYOTA VITZ (2014–2019) ───────────────────────────────────────
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Vitz', 'vehicle_year_from' => 2014, 'vehicle_year_to' => 2019, 'part_name' => 'Engine Oil Filter',        'part_category' => 'Engine',      'oem_part_number' => '90915-YZZD2',  'alternative_part_number' => 'W67',      'brand' => 'Toyota Genuine', 'description' => 'OEM oil filter for Toyota Vitz 1.0L/1.3L 1KR-FE/1NR-FE engine. Replace every 5,000 km.'],
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Vitz', 'vehicle_year_from' => 2014, 'vehicle_year_to' => 2019, 'part_name' => 'Air Filter',               'part_category' => 'Engine',      'oem_part_number' => '17801-40030',  'alternative_part_number' => 'A1633',    'brand' => 'Toyota Genuine', 'description' => 'Engine air filter for Toyota Vitz KSP130 1.0L/1.3L engine.'],
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Vitz', 'vehicle_year_from' => 2014, 'vehicle_year_to' => 2019, 'part_name' => 'Spark Plugs (Set of 3)',   'part_category' => 'Engine',      'oem_part_number' => '90919-01247',  'alternative_part_number' => 'IFR5E11',  'brand' => 'Denso',          'description' => 'Iridium spark plugs for Toyota Vitz 1.0L 1KR-FE 3-cylinder engine.'],
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Vitz', 'vehicle_year_from' => 2014, 'vehicle_year_to' => 2019, 'part_name' => 'Front Brake Pads',        'part_category' => 'Brakes',      'oem_part_number' => '04465-52220',  'alternative_part_number' => 'D1187',    'brand' => 'Toyota Genuine', 'description' => 'Front disc brake pads for Toyota Vitz KSP130 series.'],
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Vitz', 'vehicle_year_from' => 2014, 'vehicle_year_to' => 2019, 'part_name' => 'Cabin Air Filter',         'part_category' => 'Interior',    'oem_part_number' => '87139-52040',  'alternative_part_number' => 'CAF1827',  'brand' => 'Toyota Genuine', 'description' => 'Cabin pollen filter for Toyota Vitz KSP130. Replace every 15,000 km.'],
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Vitz', 'vehicle_year_from' => 2014, 'vehicle_year_to' => 2019, 'part_name' => 'Wiper Blade Set',          'part_category' => 'Exterior',    'oem_part_number' => '85212-52200',  'alternative_part_number' => 'WB-VT14',  'brand' => 'Bosch',          'description' => 'Front wiper blade set for Toyota Vitz KSP130. Driver 600mm, passenger 350mm.'],
            ['vehicle_make' => 'Toyota', 'vehicle_model' => 'Vitz', 'vehicle_year_from' => 2014, 'vehicle_year_to' => 2019, 'part_name' => 'Fuel Filter',              'part_category' => 'Fuel System', 'oem_part_number' => '23300-40050',  'alternative_part_number' => 'FF0138',   'brand' => 'Toyota Genuine', 'description' => 'In-line fuel filter for Toyota Vitz. Keeps injectors and fuel system clean.'],

        ];

        foreach ($parts as $part) {
            Part::firstOrCreate(
                [
                    'oem_part_number' => $part['oem_part_number'],
                    'vehicle_make'    => $part['vehicle_make'],
                    'vehicle_model'   => $part['vehicle_model'],
                ],
                $part
            );
        }
    }
}
